# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='postimages'),
        ),
    ]
