# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='postimages'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
